name: Deploy
on:
  push:
    branches: [ main ] # S'executa cada vegada que puges canvis a main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install --legacy-peer-deps
          npm run build
        env:
          VITE_BREVO_API_KEY: ${{ secrets.VITE_BREVO_API_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # La carpeta que crea Vite
          branch: gh-pages # La branca on GitHub guarda la web